### ISSUE TITLE
variable PLAY_SERVICES_VERSION not honored

### ISSUE THREAD

**Issue by gartorware** [dpa99c/cordova-android-play-services-gradle-release#11]
**I'm submitting a ...**  (check one with "x"):
- [x] bug report
- [ ] feature request
- [ ] documentation issue

# Bug report

**Current behavior:**

Last version of this plugin is not honoring --variable PLAY_SERVICES_VERSION.  Builds are using default 15.+ version.

See final paragraph of steps to reproduce.

**Expected behavior:**

PLAY_SERVICES_VERSION variable should be honored.

**Steps to reproduce:**

I have added this plugin with this command:
`ionic cordova plugin add cordova-android-play-services-gradle-release --variable PLAY_SERVICES_VERSION=11+.`
I can see the variable saved in config.xml. But when building the app I can see this log
```
cordova-android-play-services-gradle-release.after-prepare: Wrote custom version '11+' to ......../platforms/android/build.gradle
cordova-android-play-services-gradle-release.before-prepare: Wrote custom version '11+' to ....../platforms/android/cordova-android-play-services-gradle-release/properties.gradle
Android Studio project detected

cordova-android-play-services-gradle-release.after-prepare: Wrote custom version '11+' to ...../platforms/android/build.gradle
Preparing Firebase on Android

Configuration 'compile' in project ':app' is deprecated. Use 'implementation' instead.
+-----------------------------------------------------------------
| cordova-android-play-services-gradle-release: 15.+
+-----------------------------------------------------------------
```
If I check those files I can see that script has indeed wrote custom version correctly, but the build is still using 15.+ (default).

The build properly uses this custom version if  I open the gradle script and write 
`def PLAY_SERVICES_VERSION = "11.+"`

**Environment information**
```
cli packages: 

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0

local packages:

    @ionic/app-scripts : 3.1.9
    Cordova Platforms  : android 7.1.0
    Ionic Framework    : ionic-angular 3.8.0

System:

    Android SDK Tools : 26.1.1
    Node              : v6.14.1
    npm               : 3.10.10
    OS                : Linux 4.13
```

**Comment by dpa99c** [comment]
Fixed in `@1.4.0`
