### ISSUE TITLE
please apply google-services plugin at the bottom of the build file.

### ISSUE THREAD

**Issue by JeongJun-Lee** [dpa99c/cordova-android-play-services-gradle-release#12]
What do I add at the bottom of build.gradle by recommendation of this plugin like below?

google-services plugin could not detect any version for com.google.android.gms or com.google.firebase, default version: 9.0.0 will be used.

please apply google-services plugin at the bottom of the build file.
+-----------------------------------------------------------------
| cordova-android-play-services-gradle-release: 15.+
+----------------------------------------------------------------

**Comment by JeongJun-Lee** [comment]
And I reinstalled this plugin by this command:

cordova plugin add cordova-android-play-services-gradle-release --variable PLAY_SERVICES_VERSION=9.0.0 --fetch

The warning is disappeared but these errors happened that some dependencies are not exist like below. Those dependancies are required by com.google.firebase:firebase-core:15.0.2.

Could not find com.google.android.gms:play-services-stats:9.0.0. 
Could not find com.google.android.gms:play-services-measurement-base:9.0.0.
Could not find com.google.android.gms:play-services-ads-identifier:9.0.0.

Those files are really not exist in my local Android SDK directory, Android/sdk/extras/android/m2repository/com/google/android/gms/. And I already installed the both recent Goolgle Repository and Google Play Services by Android SDK manager.

How can I solve this issue?

Thanks in advance.

**Comment by dpa99c** [comment]
You may need install/update Android Support Repository in SDK Manager.

**Comment by JeongJun-Lee** [comment]
Thanks, but I have already installed the recent Android Support Repository.

**Comment by dpa99c** [comment]
I just noticed you are using firebase v15.0.2 - the Play Services major version must match the Firebase major version. 
So these components which Firebase v15 is requesting, e.g. [play-services-stats](https://mvnrepository.com/artifact/com.google.android.gms/play-services-stats), don't exist in Play Services v9.0.0 - they were added in v15.

So try: 

	cordova plugin rm cordova-android-play-services-gradle-release && cordova plugin add cordova-android-play-services-gradle-release --variable PLAY_SERVICES_VERSION=15.+
	cordova platform rm android --nosave && cordova platform add android --nosave
	cordova build android


You may also need v27 of support library:

	cordova plugin add cordova-android-support-gradle-release  --variable ANDROID_SUPPORT_VERSION=27.+

**Comment by JeongJun-Lee** [comment]
Thank you for your kind recommendation. I applied all things you recommended. But still errors there like below.

...
:processDebugGoogleServices

Found com.google.android.gms:play-services-auth:+, but version 9.0.0 is needed for the google-services plugin.

Found com.google.android.gms:play-services-identity:+, but version 9.0.0 is needed for the google-services plugin.
Found com.google.android.gms:play-services-location:+, but version 9.0.0 is needed for the google-services plugin.
:processDebugGoogleServices 
FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processDebugGoogleServices'.
> Please fix the version conflict either by updating the version of the google-services plugin (information about the latest version is available at https://bintray.com/android/android-tools/com.google.gms.google-services/) or updating the version of com.google.android.gms to 9.0.0.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info
 or --debug option to get more log output.

BUILD FAILED

Total time: 20.531 secs
Error: /platforms/android/gradlew: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processDebugGoogleServices'.
> Please fix the version conflict either by updating the version of the google-services plugin (information about the latest version is available at https://bintray.com/android/android-tools/com.google.gms.google-services/) or updating the version of com.google.android.gms to 9.0.0.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

[ERROR] An error occurred while running cordova run android (exit code 1).

**Comment by dpa99c** [comment]
This is most likely caused by a conflict between plugins in your project, at least one of which includes the google-services plugin.
This plugin can't help with that as it's unable to override the version of the Play Services library requested by the google-services plugin.

So the solution is probably going to be to either modify the plugins in your project or to manually fix the Gradle settings in `platforms/android/`.

For example:
- https://github.com/fechanique/cordova-plugin-fcm/issues/90
- https://github.com/fechanique/cordova-plugin-fcm/issues/319
