### ISSUE TITLE
Installing android version 6 but runs script for android 7

### ISSUE THREAD

**Issue by ilyasfoo** [dpa99c/cordova-android-play-services-gradle-release#13]
**I'm submitting a ...**  (check one with "x"):
- [ x ] bug report
- [ ] feature request
- [ ] documentation issue

# Bug report

**Current behavior:**

When I run `ionic cordova platform add android@6.4.0`, the plugin is installing with android version 7 instead, with the following error:
```
npm install of external dependencies ok
cordova-android-play-services-gradle-release: Android platform: cordova-android@7
cordova-android-play-services-gradle-release: ERROR: EXCEPTION: Error: ENOENT: no such file or directory, open 'W:\app\platforms\android\app\build.gradle'
cordova-android-support-gradle-release: Android platform: cordova-android@7
cordova-android-support-gradle-release: ERROR: EXCEPTION: Error: ENOENT: no such file or directory, open 'W:\app\platforms\android\app\build.gradle'
--save flag or autosave detected
Saving android@~6.4.0 into config.xml file ...
```
I suspected this is because of the function `getCordovaAndroidVersion` is assuming android version 7 based on the existence of the path `platforms/android/app/src`. The folder might be created by another plugin I have installed. I'm not sure if this is the standard to version detect as i'm not well versed with Cordova ecosystem, but I'd like to think that there should be a better failsafe way to determine the version. If you have any pointers I would love to make a PR.

**Steps to reproduce:**

1. Install the plugins I used
1. Add android platform 6.4.0 `ionic cordova platform add android@6.4.0`

**Environment information**

- Cordova CLI version: `7.1.0`
- Cordova platform version: `6.4.0`
- Plugins & versions installed in project (including this plugin)
```
cordova-android-play-services-gradle-release 1.4.1 "cordova-android-play-services-gradle-release"
cordova-android-support-gradle-release 1.4.2 "cordova-android-support-gradle-release"
cordova-plugin-advanced-http 1.11.1 "Advanced HTTP plugin"
cordova-plugin-camera 4.0.3 "Camera"
cordova-plugin-crosswalk-webview 2.4.0 "Crosswalk WebView Engine"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-fcm 2.1.2 "FCMPlugin"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-googlemaps 2.3.4 "cordova-plugin-googlemaps"
cordova-plugin-ionic-keyboard 2.1.2 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 1.2.1 "cordova-plugin-ionic-webview"
cordova-plugin-network-information 2.0.1 "Network Information"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-telerik-imagepicker 2.2.0 "ImagePicker"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-sqlite-storage 2.3.2 "Cordova sqlite storage plugin"
```
- Dev machine OS and version, e.g.
    - Windows 10: `Version 1709 (OS Build 16299.431)`
      
_Android build issue:_	
- Node JS version: `v6.9.4`
- Gradle version: `com.android.tools.build:gradle:3.0.0`
- Target Android SDK version
	- `android:targetSdkVersion` in `AndroidManifest.xml`: `26`
	

_If using an [Ionic Native Typescript wrapper]() for this plugin:_
- Ionic environment info
```
cli packages: (C:\Users\User\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 7.1.0

local packages:

    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : none
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    Node              : v6.9.4
    npm               : 3.10.10
    OS                : Windows 10

Environment Variables:

    ANDROID_HOME : C:\Users\User\AppData\Local\Android\Sdk

Misc:

    backend : pro
```
- Installed Ionic Native modules and versions
```
+-- @ionic-native/core@4.7.0
+-- @ionic-native/fcm@4.7.0
+-- @ionic-native/geolocation@4.5.3
+-- @ionic-native/google-maps@4.8.2
+-- @ionic-native/http@4.5.3
+-- @ionic-native/image-picker@4.7.0
+-- @ionic-native/network@4.5.3
+-- @ionic-native/splash-screen@4.5.3
+-- @ionic-native/status-bar@4.5.3
```

**Comment by wilfredonoyola** [comment]
I have the same bug :(, I need help you about this.

**Comment by dpa99c** [comment]
Fix published in `cordova-android-play-services-gradle-release@1.4.2`
