### ISSUE TITLE
May your plugin help me ? 

### ISSUE THREAD

**Issue by Cowprod** [dpa99c/cordova-android-play-services-gradle-release#3]
I'm trying to align version to build a corova app using cordova-plugin-fcm and cordova-plugin-health 

This similar issue point to your project 

https://github.com/dpa99c/cordova-plugin-request-location-accuracy/issues/21

But it does not seem to help

Steps to the error

$ cordova create bg2
$ cd bg2
$ cordova platform add android

I drop google-services.json and GoogleService-Info.plist files to the bg2 folder
I change io.cordova.hellocordova to my app Id in confix.xml

$ cordova plugin add cordova-plugin-fcm
$ cordova plugin add cordova-plugin-health
$ cordova plugin add cordova-android-play-services-gradle-release
$ cordova build android

and still the same error

Error: /Users/eimbernon/bg2/platforms/android/gradlew: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processDebugGoogleServices'.
> Please fix the version conflict either by updating the version of the google-services plugin (information about the latest version is available at https://bintray.com/android/android-tools/com.google.gms.google-services/) or updating the version of com.google.android.gms to 9.0.0.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by dpa99c** [comment]
As @christocracy [has pointed out](https://github.com/dpa99c/cordova-plugin-request-location-accuracy/issues/35#issuecomment-325693086), the problem with `cordova-plugin-fcm` is that it [sets the Gradle config using a class not a string](https://github.com/fechanique/cordova-plugin-fcm/blob/master/src/android/FCMPlugin.gradle#L13) which means this plugin is not able to override the version. The same goes for `phonegap-plugin-push`.

There is a suggested workaround [here](https://github.com/fechanique/cordova-plugin-fcm/issues/350) for `cordova-plugin-fcm`.

**Comment by Cowprod** [comment]
Thank you for your so fast answer !
I'll give it a try

regards
