### ISSUE TITLE
build failed if no plugin is injected via config.xml

### ISSUE THREAD

**Issue by iwan-uschka** [dpa99c/cordova-android-play-services-gradle-release#4]
If i don't have any plugin which needs to be configured in the config.xml, `cordova-android-play-services-gradle-release` produces an error

```
Error: Cannot read property 'length' of undefined
```

Please have a look at `scripts/before-prepare.js#15` of the current release version where `plugins` also can be undefined.

thx

**Comment by fredericagez** [comment]
Have the same issue

**Comment by dpa99c** [comment]
Fixed by c04ea2ad9a532fcf0451219b0101398c6fd750f0
